import json
import os

def generate_space_fractions_project():
    if not os.path.exists('architecture_input.json'):
        print("Error: architecture_input.json not found! Run parser.py first.")
        return

    output_dir = "generated_project"
    public_dir = os.path.join(output_dir, "public")
    os.makedirs(public_dir, exist_ok=True)

    print("Generating Space Fractions project files...")

    # 1. Write package.json
    package_data = {
        "name": "space-fractions",
        "version": "1.0.0",
        "main": "server.js",
        "scripts": { "start": "node server.js" },
        "dependencies": { "express": "^4.18.2", "cors": "^2.8.5" }
    }
    with open(os.path.join(output_dir, 'package.json'), 'w', encoding='utf-8') as f:
        json.dump(package_data, f, indent=2)

    # 2. Write server.js
    server_lines = [
        "const express = require('express');",
        "const cors = require('cors');",
        "const path = require('path');",
        "const app = express();",
        "const PORT = process.env.PORT || 3000;",
        "app.use(cors());",
        "app.use(express.json());",
        "app.use(express.static(path.join(__dirname, 'public')));",
        "app.get('/play', (req, res) => { res.json({ gameId: 101, status: 'Game Started' }); });",
        "app.listen(PORT, () => { console.log('Server running on port ' + PORT); });"
    ]
    with open(os.path.join(output_dir, 'server.js'), 'w', encoding='utf-8') as f:
        f.write("\n".join(server_lines))

    # 3. Write public/index.html (Clean Text UI)
    html_lines = [
        "<!DOCTYPE html>",
        "<html>",
        "<head>",
        "  <title>Space Fractions</title>",
        "  <style>",
        "    body { background: #0b0d1b; color: white; font-family: sans-serif; text-align: center; padding: 50px; }",
        "    .box { background: #161b33; border: 2px solid #4a4e69; padding: 30px; border-radius: 10px; display: inline-block; }",
        "    button { background: #3f37c9; color: white; border: none; padding: 12px 24px; font-size: 18px; margin: 8px; cursor: pointer; border-radius: 6px; }",
        "    button:hover { background: #4895ef; }",
        "  </style>",
        "</head>",
        "<body>",
        "  <div class='box'>",
        "    <h1>Space Fractions</h1>",
        "    <p>Mission Question: Solve <strong>1/4 + 2/4 = ?</strong></p>",
        "    <div>",
        "      <button onclick=\"alert('Correct! High score achieved!')\">3/4</button>",
        "      <button onclick=\"alert('Incorrect! Try again.')\">2/4</button>",
        "      <button onclick=\"alert('Incorrect! Try again.')\">1/2</button>",
        "    </div>",
        "  </div>",
        "</body>",
        "</html>"
    ]
    with open(os.path.join(public_dir, 'index.html'), 'w', encoding='utf-8') as f:
        f.write("\n".join(html_lines))

    # 4. Write game_ddl.sql
    with open(os.path.join(output_dir, 'game_ddl.sql'), 'w', encoding='utf-8') as f:
        f.write("CREATE TABLE games (id SERIAL PRIMARY KEY, game_state JSONB NOT NULL);\n")

    # 5. Write Dockerfile
    with open(os.path.join(output_dir, 'Dockerfile'), 'w', encoding='utf-8') as f:
        f.write("FROM node:18-alpine\nWORKDIR /app\nCOPY . .\nRUN npm install\nEXPOSE 3000\nCMD [\"npm\", \"start\"]\n")

    # 6. Write README.md
    with open(os.path.join(output_dir, 'README.md'), 'w', encoding='utf-8') as f:
        f.write("# Space Fractions\nInteractive learning tool generated by Code Agent.\n")

    print("\nSuccess! Created 'generated_project' folder with all code files inside.")

if __name__ == "__main__":
    generate_space_fractions_project()