const express = require('express');
const cors = require('cors');
const path = require('path');
const app = express();
const PORT = process.env.PORT || 3000;
app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));
app.get('/play', (req, res) => { res.json({ gameId: 101, status: 'Game Started' }); });
app.listen(PORT, () => { console.log('Server running on port ' + PORT); });